/**
 * UI strings for the cloud build. Spread into the main UI tree in src/i18n/ui.ts so the
 * classic `t('account.signIn')` lookup works; kept here so merges from main never touch
 * the same lines.
 */
export const CLOUD_UI = {
  account: {
    title: { ru: 'Аккаунт', kk: 'Аккаунт', en: 'Account' },
    signIn: { ru: 'Войти', kk: 'Кіру', en: 'Sign in' },
    signUp: { ru: 'Создать аккаунт', kk: 'Аккаунт ашу', en: 'Create account' },
    signOut: { ru: 'Выйти', kk: 'Шығу', en: 'Sign out' },
    signOutKeeps: {
      ru: 'Копия прогресса на этом устройстве останется. Чтобы убрать и её — «Выйти и очистить устройство».',
      kk: 'Осы құрылғыдағы прогресс көшірмесі қалады. Оны да өшіру үшін — «Шығу және құрылғыны тазалау».',
      en: 'The copy on this device stays. To remove it too, use "Sign out and clear this device".',
    },
    signOutClear: { ru: 'Выйти и очистить устройство', kk: 'Шығу және құрылғыны тазалау', en: 'Sign out and clear this device' },
    signOutClearText: {
      ru: 'Прогресс на этом устройстве будет удалён. В облаке он сохранится, и вы увидите его после входа.',
      kk: 'Осы құрылғыдағы прогресс өшіріледі. Бұлтта сақталады, кіргенде қайта көресіз.',
      en: 'Progress on this device will be deleted. It stays in the cloud and comes back when you sign in.',
    },
    email: { ru: 'Электронная почта', kk: 'Электрондық пошта', en: 'Email' },
    password: { ru: 'Пароль', kk: 'Құпиясөз', en: 'Password' },
    passwordHint: { ru: 'Не короче 8 символов', kk: 'Кемінде 8 таңба', en: 'At least 8 characters' },
    magicLink: { ru: 'Прислать ссылку для входа без пароля', kk: 'Құпиясөзсіз кіру сілтемесін жіберу', en: 'Email me a sign-in link instead' },
    magicLinkSent: {
      ru: 'Ссылка отправлена на {email}. Откройте её в этом же браузере — иначе вход не сработает.',
      kk: '{email} мекенжайына сілтеме жіберілді. Оны осы браузерде ашыңыз — әйтпесе кіру жұмыс істемейді.',
      en: 'A link is on its way to {email}. Open it in this same browser, or the sign-in will not work.',
    },
    confirmSent: {
      ru: 'Письмо с подтверждением отправлено на {email}. Откройте ссылку из него в этом же браузере.',
      kk: 'Растау хаты {email} мекенжайына жіберілді. Ондағы сілтемені осы браузерде ашыңыз.',
      en: 'A confirmation mail went to {email}. Open its link in this same browser.',
    },
    consent: {
      ru: 'Я согласен на хранение моей почты и данных роадмапа в облаке',
      kk: 'Поштам мен жол картасы деректерінің бұлтта сақталуына келісемін',
      en: 'I agree to my email and roadmap data being stored in the cloud',
    },
    privacy: {
      ru: 'Что хранится: почта, ответы онбординга, отмеченные шаги, документы, заметки и даты. Где: база Supabase в ЕС или Сингапуре — региона в Казахстане у сервиса нет. Кто видит: вы и администраторы сайта, включая заметки. Удалить всё можно кнопкой «Удалить аккаунт».',
      kk: 'Не сақталады: пошта, онбординг жауаптары, белгіленген қадамдар, құжаттар, жазбалар мен күндер. Қайда: ЕО не Сингапурдағы Supabase базасы — қызметтің Қазақстанда аймағы жоқ. Кім көреді: сіз және сайт әкімшілері, жазбаларды қоса. Бәрін «Аккаунтты жою» түймесімен өшіруге болады.',
      en: 'What is stored: your email, onboarding answers, ticked steps, documents, notes and dates. Where: a Supabase database in the EU or Singapore — the service has no region in Kazakhstan. Who sees it: you and the site administrators, notes included. Everything can be removed with "Delete account".',
    },
    why: {
      ru: 'Аккаунт не обязателен. Он нужен, чтобы прогресс сохранялся в облаке и открывался с любого устройства.',
      kk: 'Аккаунт міндетті емес. Ол прогрестің бұлтта сақталып, кез келген құрылғыдан ашылуы үшін керек.',
      en: 'An account is optional. It keeps your progress in the cloud and opens it on any device.',
    },
    signedInAs: { ru: 'Вы вошли как', kk: 'Сіз кірдіңіз', en: 'Signed in as' },
    roleUser: { ru: 'пользователь', kk: 'пайдаланушы', en: 'user' },
    roleAdmin: { ru: 'администратор', kk: 'әкімші', en: 'administrator' },
    changePassword: { ru: 'Сменить пароль', kk: 'Құпиясөзді өзгерту', en: 'Change password' },
    newPassword: { ru: 'Новый пароль', kk: 'Жаңа құпиясөз', en: 'New password' },
    passwordChanged: { ru: 'Пароль изменён', kk: 'Құпиясөз өзгертілді', en: 'Password changed' },
    deleteAccount: { ru: 'Удалить аккаунт', kk: 'Аккаунтты жою', en: 'Delete account' },
    deleteAccountText: {
      ru: 'Аккаунт и облачная копия прогресса будут удалены безвозвратно. Копия на этом устройстве останется.',
      kk: 'Аккаунт пен прогрестің бұлттағы көшірмесі біржола жойылады. Осы құрылғыдағы көшірме қалады.',
      en: 'The account and its cloud copy of your progress will be deleted for good. The copy on this device stays.',
    },
    download: { ru: 'Скачать копию', kk: 'Көшірмені жүктеу', en: 'Download a copy' },
    adminTitle: { ru: 'Администрирование', kk: 'Әкімшілік', en: 'Administration' },
    adminText: { ru: 'Пользователи, прогресс, статистика и роли.', kk: 'Пайдаланушылар, прогресс, статистика және рөлдер.', en: 'Users, progress, statistics and roles.' },
    openAdmin: { ru: 'Открыть панель', kk: 'Панельді ашу', en: 'Open the panel' },
    notConfigured: {
      ru: 'В этой сборке облако не настроено: приложение работает только локально. Владельцу нужно задать VITE_SUPABASE_URL и VITE_SUPABASE_ANON_KEY.',
      kk: 'Бұл жинақта бұлт бапталмаған: қолданба тек жергілікті жұмыс істейді. Иесі VITE_SUPABASE_URL мен VITE_SUPABASE_ANON_KEY орнатуы керек.',
      en: 'The cloud is not configured in this build; the app works locally only. The owner needs to set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.',
    },
    errInvalidCredentials: { ru: 'Неверная почта или пароль', kk: 'Пошта не құпиясөз қате', en: 'Wrong email or password' },
    errNotConfirmed: { ru: 'Почта ещё не подтверждена — откройте письмо', kk: 'Пошта әлі расталмаған — хатты ашыңыз', en: 'Email not confirmed yet — open the mail' },
    errRate: { ru: 'Слишком много писем подряд. Подождите несколько минут', kk: 'Хаттар тым жиі. Бірнеше минут күтіңіз', en: 'Too many emails in a row. Wait a few minutes' },
    errWeak: { ru: 'Пароль слишком простой', kk: 'Құпиясөз тым қарапайым', en: 'Password is too weak' },
    errExists: { ru: 'Такой аккаунт уже есть — войдите', kk: 'Мұндай аккаунт бар — кіріңіз', en: 'This account already exists — sign in' },
    errNetwork: { ru: 'Нет связи с сервером', kk: 'Сервермен байланыс жоқ', en: 'Cannot reach the server' },
    errLastAdmin: { ru: 'Последний администратор не может удалить аккаунт', kk: 'Соңғы әкімші аккаунтты жоя алмайды', en: 'The last administrator cannot delete their account' },
    errUnknown: { ru: 'Не получилось. Попробуйте ещё раз', kk: 'Болмады. Тағы көріңіз', en: 'That did not work. Try again' },
    backTo: { ru: 'Вернуться', kk: 'Оралу', en: 'Go back' },
  },
  sync: {
    idle: { ru: 'Не синхронизировано', kk: 'Синхрондалмаған', en: 'Not synced' },
    saving: { ru: 'Сохраняется…', kk: 'Сақталуда…', en: 'Saving…' },
    saved: { ru: 'Сохранено в облаке', kk: 'Бұлтта сақталды', en: 'Saved to the cloud' },
    error: { ru: 'Ошибка сохранения', kk: 'Сақтау қатесі', en: 'Could not save' },
    offline: { ru: 'Нет сети — сохраним при подключении', kk: 'Желі жоқ — қосылғанда сақтаймыз', en: 'Offline — will save when back online' },
    outdated: { ru: 'В облаке более новая версия данных. Обновите страницу', kk: 'Бұлтта деректердің жаңарақ нұсқасы. Бетті жаңартыңыз', en: 'The cloud has a newer data format. Reload the page' },
    conflict: { ru: 'Нужно выбрать, какую копию оставить', kk: 'Қай көшірмені қалдыратынын таңдау керек', en: 'Choose which copy to keep' },
    lastSaved: { ru: 'Последнее сохранение', kk: 'Соңғы сақтау', en: 'Last saved' },
    now: { ru: 'Синхронизировать сейчас', kk: 'Қазір синхрондау', en: 'Sync now' },
    title: { ru: 'Облако', kk: 'Бұлт', en: 'Cloud' },
    cardAnon: {
      ru: 'Войдите, чтобы прогресс сохранялся в облаке и был доступен с другого устройства.',
      kk: 'Прогресс бұлтта сақталып, басқа құрылғыдан ашылуы үшін кіріңіз.',
      en: 'Sign in to keep your progress in the cloud and open it from another device.',
    },
    resetNote: {
      ru: 'Сброс прогресса действует и на облачную копию.',
      kk: 'Прогресті қалпына келтіру бұлттағы көшірмеге де қолданылады.',
      en: 'Resetting progress also clears the cloud copy.',
    },
    chooseTitle: { ru: 'На этом устройстве уже есть прогресс', kk: 'Бұл құрылғыда прогресс бар', en: 'This device already has progress' },
    chooseText: {
      ru: 'В облаке под этим аккаунтом тоже есть копия, и они отличаются. Какую оставить? Вторая сохранится как резервная — её можно вернуть в настройках.',
      kk: 'Осы аккаунтта бұлтта да көшірме бар және олар әртүрлі. Қайсысын қалдырамыз? Екіншісі резерв ретінде сақталады — оны баптаудан қайтаруға болады.',
      en: 'The cloud also has a copy under this account, and the two differ. Which one should win? The other is kept as a backup you can restore from Settings.',
    },
    chooseCloud: { ru: 'Взять из облака', kk: 'Бұлттан алу', en: 'Use the cloud copy' },
    chooseDevice: { ru: 'Загрузить с этого устройства', kk: 'Осы құрылғыдан жүктеу', en: 'Upload this device' },
    backupTitle: { ru: 'Резервная копия', kk: 'Резервтік көшірме', en: 'Backup copy' },
    backupText: {
      ru: 'Копия прогресса, которая проиграла при слиянии {date}. Её можно вернуть или скачать.',
      kk: '{date} біріктіру кезінде ұтылған прогресс көшірмесі. Оны қайтаруға не жүктеуге болады.',
      en: 'The copy that lost the merge on {date}. It can be restored or downloaded.',
    },
    restoreBackup: { ru: 'Вернуть эту копию', kk: 'Осы көшірмені қайтару', en: 'Restore this copy' },
    legacyTitle: { ru: 'Есть прогресс из обычной версии', kk: 'Қарапайым нұсқадан прогресс бар', en: 'Progress from the classic version found' },
    legacyText: {
      ru: 'В этом браузере сохранён роадмап обычной версии Bolashak Way. Перенести его сюда?',
      kk: 'Бұл браузерде Bolashak Way қарапайым нұсқасының жол картасы сақталған. Осында көшіру керек пе?',
      en: 'This browser holds a roadmap from the classic Bolashak Way. Bring it over?',
    },
    legacyImport: { ru: 'Перенести', kk: 'Көшіру', en: 'Bring it over' },
    legacySkip: { ru: 'Не нужно', kk: 'Керек емес', en: 'No, thanks' },
  },
  admin: {
    title: { ru: 'Панель администратора', kk: 'Әкімші панелі', en: 'Admin panel' },
    overview: { ru: 'Обзор', kk: 'Шолу', en: 'Overview' },
    users: { ru: 'Пользователи', kk: 'Пайдаланушылар', en: 'Users' },
    roles: { ru: 'Роли', kk: 'Рөлдер', en: 'Roles' },
    usersTotal: { ru: 'аккаунтов', kk: 'аккаунт', en: 'accounts' },
    onboarded: { ru: 'собрали роадмап', kk: 'жол картасын жинады', en: 'built a roadmap' },
    active7: { ru: 'активны за 7 дней', kk: '7 күнде белсенді', en: 'active in 7 days' },
    active30: { ru: 'активны за 30 дней', kk: '30 күнде белсенді', en: 'active in 30 days' },
    admins: { ru: 'администраторов', kk: 'әкімші', en: 'administrators' },
    byTrack: { ru: 'По трекам', kk: 'Трек бойынша', en: 'By track' },
    byCategory: { ru: 'По категориям', kk: 'Санат бойынша', en: 'By category' },
    funnel: { ru: 'Где сейчас люди: по главам', kk: 'Адамдар қазір қайда: тарау бойынша', en: 'Where people are: by chapter' },
    byStage: { ru: 'Текущий этап', kk: 'Ағымдағы кезең', en: 'Current stage' },
    completed: { ru: 'Прошли весь путь', kk: 'Бүкіл жолды өтті', en: 'Finished the path' },
    buckets: { ru: 'Распределение прогресса', kk: 'Прогресс таралуы', en: 'Progress distribution' },
    signups: { ru: 'Регистрации по неделям', kk: 'Апта бойынша тіркелу', en: 'Sign-ups by week' },
    activity: { ru: 'Активные пользователи по дням', kk: 'Күн бойынша белсенді пайдаланушылар', en: 'Active users by day' },
    generatedAt: { ru: 'Данные на', kk: 'Деректер', en: 'Data as of' },
    refresh: { ru: 'Обновить', kk: 'Жаңарту', en: 'Refresh' },
    search: { ru: 'Поиск по почте', kk: 'Пошта бойынша іздеу', en: 'Search by email' },
    filterTrack: { ru: 'Трек', kk: 'Трек', en: 'Track' },
    filterCategory: { ru: 'Категория', kk: 'Санат', en: 'Category' },
    filterChapter: { ru: 'Глава', kk: 'Тарау', en: 'Chapter' },
    filterRole: { ru: 'Роль', kk: 'Рөл', en: 'Role' },
    any: { ru: 'Все', kk: 'Барлығы', en: 'All' },
    noProgress: { ru: 'Без роадмапа', kk: 'Жол картасысыз', en: 'No roadmap' },
    colEmail: { ru: 'Почта', kk: 'Пошта', en: 'Email' },
    colCategory: { ru: 'Категория', kk: 'Санат', en: 'Category' },
    colStage: { ru: 'Текущий этап', kk: 'Ағымдағы кезең', en: 'Current stage' },
    colProgress: { ru: 'Прогресс', kk: 'Прогресс', en: 'Progress' },
    colActivity: { ru: 'Активность', kk: 'Белсенділік', en: 'Activity' },
    colRole: { ru: 'Роль', kk: 'Рөл', en: 'Role' },
    colSignedUp: { ru: 'Регистрация', kk: 'Тіркелу', en: 'Signed up' },
    shown: { ru: 'Показано {n} из {total}', kk: '{total} ішінен {n} көрсетілді', en: 'Showing {n} of {total}' },
    csv: { ru: 'Скачать CSV', kk: 'CSV жүктеу', en: 'Download CSV' },
    prev: { ru: 'Назад', kk: 'Артқа', en: 'Previous' },
    next: { ru: 'Дальше', kk: 'Келесі', en: 'Next' },
    empty: { ru: 'Никого не найдено', kk: 'Ешкім табылмады', en: 'Nobody found' },
    noRoadmapYet: { ru: 'Роадмап ещё не собран', kk: 'Жол картасы әлі жиналмаған', en: 'No roadmap built yet' },
    user: { ru: 'Пользователь', kk: 'Пайдаланушы', en: 'User' },
    readOnly: { ru: 'Только просмотр', kk: 'Тек қарау', en: 'Read only' },
    stages: { ru: 'Этапы', kk: 'Кезеңдер', en: 'Stages' },
    documents: { ru: 'Документы', kk: 'Құжаттар', en: 'Documents' },
    dates: { ru: 'Даты и сроки', kk: 'Күндер мен мерзімдер', en: 'Dates and deadlines' },
    notes: { ru: 'Заметки', kk: 'Жазбалар', en: 'Notes' },
    showNotes: { ru: 'Показать заметки', kk: 'Жазбаларды көрсету', en: 'Show notes' },
    hideNotes: { ru: 'Скрыть заметки', kk: 'Жазбаларды жасыру', en: 'Hide notes' },
    notesWarning: { ru: 'Личные записи пользователя. Открывайте только по необходимости.', kk: 'Пайдаланушының жеке жазбалары. Тек қажет болғанда ашыңыз.', en: 'The user\'s private notes. Open only when needed.' },
    downloadSnapshot: { ru: 'Скачать снапшот', kk: 'Снапшотты жүктеу', en: 'Download snapshot' },
    newerSchema: {
      ru: 'Данные сохранены более новой версией приложения, чем эта. Обновите страницу, чтобы увидеть их полностью.',
      kk: 'Деректер қолданбаның осыдан жаңарақ нұсқасымен сақталған. Толық көру үшін бетті жаңартыңыз.',
      en: 'This data was saved by a newer app version than this one. Reload to see it in full.',
    },
    promote: { ru: 'Сделать администратором', kk: 'Әкімші ету', en: 'Make administrator' },
    demote: { ru: 'Снять права администратора', kk: 'Әкімші құқығын алу', en: 'Remove administrator rights' },
    promoteText: { ru: '{email} получит доступ ко всем пользователям, их прогрессу и заметкам.', kk: '{email} барлық пайдаланушыға, олардың прогресі мен жазбаларына қол жеткізеді.', en: '{email} will get access to every user, their progress and notes.' },
    demoteText: { ru: '{email} останется обычным пользователем.', kk: '{email} қарапайым пайдаланушы болып қалады.', en: '{email} will become a regular user.' },
    lastAdmin: { ru: 'Единственного администратора снять нельзя', kk: 'Жалғыз әкімшіні алуға болмайды', en: 'The only administrator cannot be removed' },
    currentAdmins: { ru: 'Текущие администраторы', kk: 'Ағымдағы әкімшілер', en: 'Current administrators' },
    findUser: { ru: 'Найти пользователя', kk: 'Пайдаланушыны табу', en: 'Find a user' },
    loading: { ru: 'Загрузка…', kk: 'Жүктелуде…', en: 'Loading…' },
    loadError: { ru: 'Не удалось загрузить данные', kk: 'Деректерді жүктеу мүмкін болмады', en: 'Could not load the data' },
    forbidden: { ru: 'Нет доступа', kk: 'Қолжетімсіз', en: 'No access' },
    you: { ru: 'это вы', kk: 'бұл сіз', en: 'that is you' },
    noData: { ru: 'Пока пусто', kk: 'Әзірге бос', en: 'Nothing yet' },
  },
} as const
