import type { DocItem } from './types'

const PREFERENTIAL = ['master_rural', 'master_engineer', 'master_medical', 'master_civil', 'master_nuclear'] as const
const WITH_EMPLOYER = ['master_civil', 'master_nuclear', 'phd_nuclear', 'internship', 'science_internship'] as const
const WITH_EXPERIENCE = ['master_rural', 'master_engineer', 'master_medical', 'master_civil', 'master_nuclear', 'phd_nuclear', 'internship', 'science_internship'] as const

/**
 * Consolidated document checklist. Items are filtered by the profile and grouped by stage
 * on the "My documents" screen.
 */
export const DOCUMENTS: DocItem[] = [
  // — Preparation —
  {
    id: 'kazakh_cert',
    stage: 'kazakh',
    title: { ru: 'Сертификат КАЗТЕСТ или Qazaq Resmi Test (B1 и выше)', kk: 'ҚАЗТЕСТ немесе Qazaq Resmi Test сертификаты (B1 және жоғары)', en: 'KAZTEST or Qazaq Resmi Test certificate (B1+)' },
    note: { ru: 'Действительный на момент подачи', kk: 'Тапсыру кезінде жарамды', en: 'Valid at the time of application' },
    source: 'prikaz318',
    autoCompleteWhen: { kazakhCert: true },
  },
  {
    id: 'foreign_cert',
    stage: 'foreign',
    title: { ru: 'Сертификат по иностранному языку', kk: 'Шет тілі сертификаты', en: 'Foreign language certificate' },
    note: { ru: 'Результат не ниже порогового уровня вашей категории', kk: 'Нәтиже санатыңыздың шекті деңгейінен төмен емес', en: 'A score at or above your category threshold' },
    source: 'prikaz318',
    appliesTo: { not: { category: ['bachelor'] } },
    autoCompleteWhen: { hasForeignCert: true },
  },
  {
    id: 'offer_letter',
    stage: 'admission',
    title: { ru: 'Документ о безусловном зачислении или приглашении', kk: 'Сөзсіз қабылдау не шақыру туралы құжат', en: 'Unconditional admission or invitation letter' },
    note: { ru: 'С данными претендента, специальностью, сроками и стоимостью, с нотариальным переводом', kk: 'Үміткер деректері, мамандық, мерзім және құн көрсетіліп, нотариалды аудармасымен', en: 'With your details, specialty, dates and cost, notarially translated' },
    source: 'pravila',
    appliesTo: { not: { category: [...PREFERENTIAL] } },
    autoCompleteWhen: { invitation: ['unconditional'] },
  },
  {
    id: 'free_tuition_docs',
    stage: 'admission',
    title: { ru: 'Документы о бесплатном обучении с полным покрытием расходов', kk: 'Шығыстары толық жабылған тегін оқу туралы құжаттар', en: 'Documents proving free tuition with full cost coverage' },
    note: { ru: 'При наличии, с нотариальным переводом', kk: 'Болған жағдайда, нотариалды аудармасымен', en: 'If applicable, notarially translated' },
    source: 'pravila',
    appliesTo: { not: { category: [...PREFERENTIAL] } },
  },
  {
    id: 'internship_programme',
    stage: 'admission',
    title: { ru: 'Программа прохождения стажировки', kk: 'Тағылымдамадан өту бағдарламасы', en: 'Internship programme' },
    note: { ru: 'Утверждена направляющей и принимающей организациями, с нотариальным переводом', kk: 'Жіберуші және қабылдаушы ұйымдар бекіткен, нотариалды аудармасымен', en: 'Approved by the sending and host organisations, notarially translated' },
    source: 'internship_program',
    form: 'internship_program',
    appliesTo: { track: ['internship'] },
  },
  {
    id: 'science_programme',
    stage: 'admission',
    title: { ru: 'Программа научной стажировки', kk: 'Ғылыми тағылымдама бағдарламасы', en: 'Scientific internship programme' },
    note: { ru: 'Утверждает работодатель, согласует зарубежная организация, с нотариальным переводом', kk: 'Жұмыс беруші бекітеді, шетелдік ұйым келіседі, нотариалды аудармасымен', en: 'Approved by your employer, agreed with the host organisation, notarially translated' },
    source: 'ns_program',
    form: 'ns_program',
    appliesTo: { track: ['science_internship'] },
  },

  // — Application package —
  {
    id: 'anketa',
    stage: 'documents',
    title: { ru: 'Анкета претендента по утверждённой форме', kk: 'Бекітілген нысандағы үміткер сауалнамасы', en: 'Applicant questionnaire on the approved form' },
    source: 'prikaz318',
  },
  {
    id: 'anketa_ns',
    stage: 'documents',
    title: { ru: 'Анкета претендента на научную стажировку', kk: 'Ғылыми тағылымдамаға үміткер сауалнамасы', en: 'Scientific internship applicant questionnaire' },
    source: 'ns_anketa',
    form: 'ns_anketa',
    appliesTo: { track: ['science_internship'] },
  },
  {
    id: 'id_passport',
    stage: 'documents',
    title: { ru: 'Удостоверение личности и паспорт', kk: 'Жеке куәлік және паспорт', en: 'ID card and passport' },
    note: { ru: 'Для научной стажировки — оригиналы и копии; оригиналы возвращают после сверки', kk: 'Ғылыми тағылымдамаға — түпнұсқа мен көшірме; түпнұсқа қайтарылады', en: 'For scientific internships — originals and copies; originals are returned' },
    source: 'pravila',
  },
  {
    id: 'diploma',
    stage: 'documents',
    title: { ru: 'Диплом бакалавра или специалиста с приложением', kk: 'Бакалавр не маман дипломы қосымшасымен', en: 'Bachelor or specialist diploma with transcript' },
    note: { ru: 'При учёбе за рубежом — удостоверение о признании или нострификации', kk: 'Шетелде оқыған болса — тану не нострификация куәлігі', en: 'If you studied abroad — a recognition or nostrification certificate' },
    source: 'pravila',
    appliesTo: { not: { track: ['bachelor'] } },
  },
  {
    id: 'school_certificate',
    stage: 'documents',
    title: { ru: 'Документ об общем среднем или техническом и профессиональном образовании с приложением', kk: 'Жалпы орта не техникалық және кәсіптік білім туралы құжат қосымшасымен', en: 'Secondary or technical-vocational education document with annex' },
    source: 'pravila',
    appliesTo: { track: ['bachelor'] },
  },
  {
    id: 'olympiad_diploma',
    stage: 'documents',
    title: { ru: 'Диплом международной олимпиады или конкурса за последние 3 года', kk: 'Соңғы 3 жылдағы халықаралық олимпиада не конкурс дипломы', en: 'International olympiad or competition diploma from the last 3 years' },
    source: 'olympiads',
    form: 'olympiads',
    appliesTo: { track: ['bachelor'] },
  },
  {
    id: 'degree_document',
    stage: 'documents',
    title: { ru: 'Документ об учёной степени с приложением', kk: 'Ғылыми дәреже туралы құжат қосымшасымен', en: 'Academic degree document with annex' },
    source: 'ns_documents',
    appliesTo: { track: ['science_internship'] },
  },
  {
    id: 'medical_072',
    stage: 'documents',
    title: { ru: 'Медицинская справка формы 072/у для выезжающего за границу', kk: 'Шетелге шығушыға 072/у нысанындағы медициналық анықтама', en: 'Medical certificate form 072/u for travel abroad' },
    source: 'pravila',
  },
  {
    id: 'motivation_letter',
    stage: 'documents',
    title: { ru: 'Мотивационное письмо (эссе до 500 слов)', kk: 'Мотивациялық хат (500 сөзге дейінгі эссе)', en: 'Motivation letter (essay up to 500 words)' },
    note: { ru: 'На казахском или русском, с датой и подписью в конце', kk: 'Қазақ не орыс тілінде, соңында күні мен қолы', en: 'In Kazakh or Russian, dated and signed at the end' },
    source: 'pravila',
    appliesTo: { not: { category: ['residency', 'phd_self', 'science_internship'] } },
  },
  {
    id: 'employment_docs',
    stage: 'documents',
    title: { ru: 'Документы о трудовой деятельности', kk: 'Еңбек қызметі туралы құжаттар', en: 'Employment documents' },
    source: 'pravila',
    appliesTo: { category: [...WITH_EXPERIENCE] },
  },
  {
    id: 'pension_statement',
    stage: 'documents',
    title: { ru: 'Выписка о перечисленных обязательных пенсионных взносах', kk: 'Аударылған міндетті зейнетақы жарналары туралы үзінді көшірме', en: 'Statement of mandatory pension contributions' },
    note: { ru: 'За требуемый период стажа, включая оплачиваемый трудовой отпуск', kk: 'Талап етілетін өтіл кезеңіне, ақылы демалысты қоса', en: 'For the required experience period, paid leave included' },
    source: 'pp573',
    appliesTo: { category: [...WITH_EXPERIENCE] },
  },
  {
    id: 'employer_request_doc',
    stage: 'documents',
    title: { ru: 'Заявка работодателя с сохранением места работы', kk: 'Жұмыс орнын сақтаумен жұмыс беруші өтінімі', en: 'Employer request with job retention' },
    source: 'employer_form',
    form: 'employer_form',
    appliesTo: { category: [...WITH_EMPLOYER] },
  },
  {
    id: 'study_plan_doc',
    stage: 'documents',
    title: { ru: 'Индивидуальный учебный план, согласованный с вузом', kk: 'ЖОО-мен келісілген жеке оқу жоспары', en: 'Individual study plan agreed with the university' },
    note: { ru: 'С нотариальным переводом', kk: 'Нотариалды аудармасымен', en: 'Notarially translated' },
    source: 'pravila',
    appliesTo: { category: ['phd_self', 'phd_nuclear'] },
  },
  {
    id: 'parent_consent_doc',
    stage: 'documents',
    title: { ru: 'Нотариальное согласие законного представителя (до 18 лет)', kk: 'Заңды өкілдің нотариалды келісімі (18 жасқа дейін)', en: 'Notarised consent of a legal representative (under 18)' },
    source: 'pravila',
    appliesTo: { track: ['bachelor'] },
  },
  {
    id: 'publications_doc',
    stage: 'documents',
    title: { ru: 'Список научных результатов, утверждённый работодателем', kk: 'Жұмыс беруші бекіткен ғылыми нәтижелер тізімі', en: 'List of research results approved by the employer' },
    note: { ru: 'Не менее одной статьи в Web of Science или Scopus либо в изданиях из Перечня', kk: 'Web of Science не Scopus-та кемінде бір мақала', en: 'At least one Web of Science or Scopus article' },
    source: 'ns_requirements',
    appliesTo: { track: ['science_internship'] },
  },
  {
    id: 'accreditation_doc',
    stage: 'documents',
    title: { ru: 'Копия свидетельства об аккредитации научной организации', kk: 'Ғылыми ұйымның аккредиттеу куәлігінің көшірмесі', en: 'Copy of the research organisation accreditation certificate' },
    source: 'ns_documents',
    appliesTo: { track: ['science_internship'] },
  },
  {
    id: 'transcript_current_doc',
    stage: 'documents',
    title: { ru: 'Документ об успеваемости от зарубежного вуза', kk: 'Шетелдік ЖОО-дан үлгерім туралы құжат', en: 'Academic performance document from the foreign university' },
    note: { ru: 'Если вы уже учитесь за рубежом, с нотариальным переводом', kk: 'Шетелде оқып жүрсеңіз, нотариалды аудармасымен', en: 'If you already study abroad, notarially translated' },
    source: 'pravila',
    appliesTo: { category: ['master_self', 'phd_self', 'residency'] },
  },
  {
    id: 'power_of_attorney',
    stage: 'apply',
    title: { ru: 'Нотариально заверенная доверенность на представителя', kk: 'Өкілге нотариалды куәландырылған сенімхат', en: 'Notarised power of attorney for a representative' },
    note: { ru: 'Если документы подаёте не лично', kk: 'Құжаттарды өзіңіз тапсырмасаңыз', en: 'If someone else submits on your behalf' },
    source: 'ns_documents',
    appliesTo: { track: ['science_internship'] },
  },

  // — After the award —
  {
    id: 'contract_docs',
    stage: 'contract',
    title: { ru: 'Документы для договора: удостоверение личности, реквизиты и учредительные документы работодателя', kk: 'Шартқа құжаттар: жеке куәлік, жұмыс берушінің деректемелері мен құрылтай құжаттары', en: 'Contract documents: ID, employer bank details and constituent documents' },
    source: 'ns_winner',
  },
  {
    id: 'guarantor_docs',
    stage: 'contract',
    title: { ru: 'Документы гаранта: копия удостоверения, справка о доходах и пенсионных отчислениях за 12 месяцев', kk: 'Кепілгер құжаттары: куәлік көшірмесі, 12 айлық табыс және зейнетақы аударымдары анықтамасы', en: 'Guarantor documents: ID copy, 12-month income and pension statements' },
    source: 'ns_winner',
  },
  {
    id: 'pledge_docs',
    stage: 'contract',
    title: { ru: 'Документы по залогу: правоустанавливающие документы, отчёт об оценке, справка о зарегистрированных правах (форма 2), нотариальные согласия', kk: 'Кепіл құжаттары: құқық белгілейтін құжаттар, бағалау есебі, тіркелген құқықтар анықтамасы (2-нысан), нотариалды келісімдер', en: 'Pledge documents: title deeds, valuation report, title certificate (form 2), notarised consents' },
    source: 'zamena_zaloga',
  },
  {
    id: 'card_details',
    stage: 'departure',
    title: { ru: 'Форма сведений по карт-счёту обладателя стипендии', kk: 'Стипендиат карт-шоты бойынша мәліметтер нысаны', en: 'Scholarship holder card-account details form' },
    source: 'finance',
    form: 'finance',
  },
  {
    id: 'guarantee_letter_doc',
    stage: 'departure',
    title: { ru: 'Заявление на письмо о финансовой гарантии', kk: 'Қаржылық кепілдік хатына өтініш', en: 'Request for the financial guarantee letter' },
    source: 'obrazcy',
    form: 'obrazcy',
  },
  {
    id: 'ticket_request',
    stage: 'departure',
    title: { ru: 'Заявление на приобретение авиабилета', kk: 'Авиабилет сатып алуға өтініш', en: 'Flight ticket request' },
    source: 'obrazcy',
    form: 'obrazcy',
  },

  // — Return and work-back —
  {
    id: 'completion_application',
    stage: 'return',
    title: { ru: 'Заявление о завершении обучения или стажировки', kk: 'Оқуды не тағылымдаманы аяқтау туралы өтініш', en: 'Study or internship completion application' },
    source: 'obrazcy',
    form: 'obrazcy',
  },
  {
    id: 'diploma_translation',
    stage: 'return',
    title: { ru: 'Нотариальные переводы диплома и транскрипта', kk: 'Диплом мен транскрипттің нотариалды аудармалары', en: 'Notarised translations of the diploma and transcript' },
    source: 'otrabotka',
    appliesTo: { not: { track: ['internship', 'science_internship'] } },
  },
  {
    id: 'entry_stamp',
    stage: 'return',
    title: { ru: 'Копия паспорта с отметкой о въезде в Казахстан', kk: 'Қазақстанға кіру белгісі бар паспорт көшірмесі', en: 'Passport copy with the Kazakhstan entry stamp' },
    source: 'otrabotka',
  },
  {
    id: 'internship_report',
    stage: 'return',
    title: { ru: 'Итоговый отчёт и отзыв руководителя стажировки', kk: 'Қорытынды есеп және тағылымдама жетекшісінің пікірі', en: 'Final report and internship supervisor feedback' },
    source: 'stipendiat_internship',
    appliesTo: { track: ['internship', 'science_internship'] },
  },
  {
    id: 'workback_certificates',
    stage: 'workback',
    title: { ru: 'Справки с места работы каждые 6 месяцев', kk: 'Әр 6 айда жұмыс орнынан анықтама', en: 'Employment certificates every 6 months' },
    note: { ru: 'С датой регистрации, номером, подписью и печатью, в PDF', kk: 'Тіркеу күні, нөмірі, қолы мен мөрі бар, PDF форматта', en: 'With registration date, number, signature and seal, as PDF' },
    source: 'otrabotka',
  },
  {
    id: 'obligations_application',
    stage: 'workback',
    title: { ru: 'Заявление об исполнении договорных обязательств', kk: 'Шарттық міндеттемелердің орындалуы туралы өтініш', en: 'Application confirming fulfilment of contractual obligations' },
    note: { ru: 'С копией трудовой книжки, выпиской о пенсионных отчислениях и характеристикой работодателя', kk: 'Еңбек кітапшасының көшірмесі, зейнетақы аударымдары үзіндісі және мінездемемен', en: 'With employment record copy, pension statement and employer reference' },
    source: 'formy_vypusknika',
    form: 'formy_vypusknika',
  },
]
