// Imports the curated FAQ CSV (Notion export) into src/content/faq.generated.ts.
// Usage: npm run import:faq   (re-run whenever the CSV is updated)
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const SRC = resolve('321/bolashak_faq_baza_notion.csv')
const OUT = resolve('src/content/faq.generated.ts')

function parseCsv(text) {
  const rows = []
  let row = [], field = '', inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ } else inQuotes = false
      } else field += c
    } else if (c === '"') inQuotes = true
    else if (c === ',') { row.push(field); field = '' }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = '' }
    else if (c !== '\r') field += c
  }
  if (field.length || row.length) { row.push(field); rows.push(row) }
  return rows
}

// Maps the CSV "Категория" to the roadmap stage that should surface the question.
const STAGE_BY_CATEGORY = {
  'Слоты и собеседование': 'interview',
  'Время и таймер': 'testing',
  'Пересдача': 'testing',
  'Ответы и сохранение': 'testing',
  'Не могу начать тест': 'testing',
  'Белый экран и зависание': 'testing',
  'Интернет и сеть': 'testing',
  'Камера и идентификация': 'testing',
  'Технические требования': 'testing',
  'Логин, пароль, доступ': 'testing',
  'Личный кабинет и заявка': 'apply',
  'Порядок и содержание тестов': 'testing',
  'Правила на тесте': 'testing',
  'Результаты и баллы': 'commission',
  'Апелляция и жалоба': 'commission',
  'Следующий тур и комиссия': 'commission',
}

const STATUS = {
  'Подтверждено': 'confirmed',
  'Частично требует уточнения': 'partial',
  'Требует уточнения': 'unverified',
}

const text = readFileSync(SRC, 'utf8').replace(/^﻿/, '')
const [header, ...rows] = parseCsv(text).filter((r) => r.some((c) => c.trim()))
const col = (name) => header.indexOf(name)
const iQ = col('Вопрос'), iA = col('Ответ'), iC = col('Категория'), iF = col('Частота в чатах'), iS = col('Статус ответа')

const items = rows.map((r, idx) => ({
  id: `faq-${String(idx + 1).padStart(2, '0')}`,
  stage: STAGE_BY_CATEGORY[r[iC].trim()] ?? 'testing',
  category: r[iC].trim(),
  frequency: Number(r[iF]) || 0,
  status: STATUS[r[iS].trim()] ?? 'unverified',
  q: r[iQ].trim(),
  a: r[iA].trim(),
}))

const esc = (s) => JSON.stringify(s)
const out = `// AUTO-GENERATED by scripts/import-faq.mjs from 321/bolashak_faq_baza_notion.csv — do not edit by hand.
// Source: curated answers of the Bolashak administration in applicant chats (May–Aug 2026).
import type { FaqItem } from './types'

export const GENERATED_FAQ: FaqItem[] = [
${items
  .map(
    (it) => `  {
    id: ${esc(it.id)},
    stage: ${esc(it.stage)},
    category: ${esc(it.category)},
    frequency: ${it.frequency},
    status: ${esc(it.status)},
    q: { ru: ${esc(it.q)} },
    a: { ru: ${esc(it.a)} },
    source: 'chat-faq',
  },`,
  )
  .join('\n')}
]
`
writeFileSync(OUT, out)
console.log(`wrote ${items.length} FAQ items → ${OUT}`)
